# Userscript configuration
[userscript]
homepageURL = "https://github.com/isandrel/Markify"
icon        = "https://cdn.jsdelivr.net/npm/@tabler/icons@latest/icons/download.svg"
license     = "AGPL-3.0-or-later"
match       = ["https://www.uscardforum.com/t/*/*"]
namespace   = "https://github.com/isandrel/Markify"
supportURL  = "https://github.com/isandrel/Markify/issues"

[userscript.grant]
permissions = [
    "GM.deleteValue",
    "GM.getValue",
    "GM.listValues",
    "GM.notification",
    "GM.openInTab",
    "GM.registerMenuCommand",
    "GM.setClipboard",
    "GM.setValue",
]

[userscript.compatible]
browsers = ["chrome", "edge", "firefox", "opera", "safari"]
